version: '3'
services:
  cross-server-bans:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    volumes:
      - .env:/app/.env
    command: ["npm", "run", "start:prod"]
